- name: copy vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: clone oh-my-zsh for users
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh'

- name: set default shell for users
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh

- name: zshlogin
  copy:
    src: zshrc
    dest: ~/.zshrc
